name: Ren'Py Autobuild + Deploy (Creeeples v1.0.0)

on:
  push:
    branches:
      - 'release/*'
      - 'prerelease/*'

jobs:
  build-renpy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Uscimento di Versione
      id: extract_version
      run: |
          echo "old GITHUB_REF is $GITHUB_REF"
          GITHUB_REF=$(echo $GITHUB_REF | sed -e "s#refs/heads/\(release\|prerelease\)/##g")
          echo "::set-output name=ref::$GITHUB_REF"
      env:
        GITHUB_REF: ${{ github.ref }}

    - name: Formaggio Nome Rilascio
      id: format_release_name
      run: |
        echo "::set-output name=release_name::Release-${{ steps.extract_version.outputs.ref }}"
      env:
        VERSION: ${{ steps.extract_version.outputs.ref }}
        
    - name: Formaggio Nome Targhetta
      id: format_tag_name
      run: |
        echo "::set-output name=tag_name::v${{ steps.extract_version.outputs.ref }}"
      env:
        VERSION: ${{ steps.extract_version.outputs.ref }}
        
    - name: Piazzamento Blocchi Lego
      id: build_project
      uses: creeeples/renpy-docker-builder@v1.0.2
      with:
        sdk-version: '8.1.1'
        project-dir: '.'
      env:
        SDL_AUDIODRIVER: dummy
        SDL_VIDEODRIVER: dummy
    - name: Setup GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ github.token }}
        tag_name: ${{ steps.format_tag_name.outputs.tag_name }}
        prerelease: ${{ startsWith(github.ref, 'refs/heads/prerelease/') }} # Set prerelease flag conditionally
      env:
          GH_TOKEN: ${{ github.token }}

    - name: Uscimento Costruzione Lego in Pubblico
      run: |
        for file in ${{ steps.build_project.outputs.dir }}/*.{zip,tar.bz2}; do
        echo "Shredding $file for sussy situation"
        asset_name=$(basename "$file")
        gh release upload ${{ steps.format_tag_name.outputs.tag_name }} "$file" --clobber
        done
      env:
          GH_TOKEN: ${{ github.token }}
